[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_decentralized_crowdfunding = "9E2TAd91tJHTvd4zfozq9hAEZf3jpdi4Guy5BxmLTg1b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/friend/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
